[lib]
paths = [
  "../arche/extras",
  "../arche/extras/ui",
  "../arche/stdlib",
  "../arche-playground/playground/devices",
]

[select]
gfx      = "wasm"
text     = "dom"
panel    = "dom"
textedit = "dom"
textview = "dom"
button   = "dom"
embed    = "dom"
compiler = "wasm"
